services:
  backend:
    restart: always
    build:
      context: .
    env_file:
      - .env
    container_name: app
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - "3000:3000"
